name: Deploy React to AWS
on:
  push:
    branches:
      - "aws-beanstalk"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: AKIAU6BHV5ARXZJYGG2W
          aws_secret_key: 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
          application_name: bean-six
          environment_name: Bean-six-env
          version_label: 11
          existing_bucket_name: elasticbeanstalk-ap-south-1-339385640995
          region: ap-south-1
          deployment_package: deploy.zip
